comment: false

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
      method: no
      macro: no

coverage:
  range: 50...90
  round: nearest
  status:
    project: off
    patch: off
    changes: off

ignore:
- tests/.*
- gui-builder/.*
- examples/.*
- include/TGUI/extlibs/.*
